site_name: Bear API
site_url: https://bearrobotics-public.github.io/cloud/
copyright: Copyright 2025 Bear Robotics, Inc. All rights reserved.
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.copy
    - content.tooltips
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    - toc.follow
    - content.tabs.link
  palette:
    primary: custom
  favicon: assets/favicon.png
  logo: assets/bear_logo_white.png
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - toc:
      permalink: True
      toc_depth: 4
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Core Concepts:
      - Mission: concepts/mission.md
      - Localization: concepts/localization.md
      - Location: concepts/location.md
      - Status: concepts/status.md
  - Cloud API Reference:
      - v1.0:
          - Core resources:
              - Mission: v1.0/resources/Mission.md
              - Map: v1.0/resources/LocationsAndMaps.md
              - Localization: v1.0/resources/Localization.md
              - Robot Status: v1.0/resources/RobotStatus.md
              - Fleet Management: v1.0/resources/FleetManagement.md
          - Carti: v1.0/resources/Carti.md
          - Servi: v1.0/resources/Servi.md
      - v0.1Beta:
          - Services:
              - Cloud API Service: v0.1/cloud/CloudApiService.md
          - Message Types:
              - Cloud:
                  - Config: v0.1/cloud/Config.md
                  - Profiles: v0.1/cloud/Profiles.md
                  - Robot Settings: v0.1/cloud/RobotSettings.md
                  - Robot Status: v0.1/cloud/RobotStatus.md
              - Common:
                  - Annotations: v0.1/common/Annotations.md
                  - Math: v0.1/common/Math.md
              - Location:
                  - Annotation: v0.1/location/Annotation.md
                  - Location: v0.1/location/Location.md
                  - Map: v0.1/location/Map.md
                  - Types: v0.1/location/Types.md
                  - Zones: v0.1/location/Zones.md
              - Robot:
                  - Localization: v0.1/robot/Localization.md
                  - Mission: v0.1/robot/Mission.md
                  - Robot: v0.1/robot/Robot.md
                  - Status: v0.1/robot/Status.md
  - Guides:
      - Setup:
          - Authentication: guides/setup/authentication.md
          - Examples:
              - Python: guides/examples/python.md
              - Golang: guides/examples/golang.md
      - Errors and Troubleshooting: guides/errors.md
  - Changelog: 
    - v1.0: changelog/v1.0.md
    - v0.1Beta: changelog/v0.1beta.md
